# Generated by Django 5.1.1 on 2024-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Starter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Topic", models.CharField(max_length=50)),
                ("Sub_topic", models.CharField(max_length=200)),
                ("Description", models.TextField()),
            ],
        ),
    ]
