# Generated by Django 5.1.1 on 2024-09-28 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Prep", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="starter",
            old_name="Description",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="starter",
            old_name="Sub_topic",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="starter",
            name="Topic",
        ),
        migrations.AddField(
            model_name="starter",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="starter",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="starter",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
